### ISSUE TITLE
[FEATURE] Change some moprh into maybe number

### ISSUE THREAD

**Issue by capashaa** [MartenM/PixelPilot#1]
I have seen that you use morph on number blocks. Maybe you could change this, so it's a bit easier to understand.
This will make me a bit lost because there are morphs like spike, but there is also numbered blocks such as coin doors.

**Comment by MartenM** [comment]
Seems like a good suggestion. I initially named them this way because I wasn't sure of any other good names.
Number seems to be quite okay though.

I did plan on extending the class at some point but that's for the future.
`NumberedBlock` -> `RotateableBlock`
`NumberedBlock` -> `MorphableBlock`
`NumberedBlock` -> `DoorBlock`

**Comment by capashaa** [comment]
I followed this [GitLab Repository](https://gitlab.com/LukeM212/EELVL/-/blob/master/EELVL/Block.cs?ref_type=heads) to name stuff on my other things before. You don't need to to that. This is only an example how to do it.

**Comment by MartenM** [comment]
`RotatableButNotReally` EHM

**Comment by capashaa** [comment]
> `RotatableButNotReally` EHM

In EE xmas presents can't be rotated, but they still use a rotation 0. This is EE lol

**Comment by MartenM** [comment]
> > `RotatableButNotReally` EHM
> 
> In EE xmas presents can't be rotated, but they still use a rotation 0. This is EE lol

Isn't that more like a morphable then?
**Edit:** Forgot that those could not be rotated or morphed. Lol what the hell hahaha

**Comment by capashaa** [comment]
> > > `RotatableButNotReally` EHM
> > 
> > 
> > In EE xmas presents can't be rotated, but they still use a rotation 0. This is EE lol
> 
> Isn't that more like a morphable then?

I think that he didn't know what to name them. The reason of just that name. Because they can't be rotated, but they still have rotation on them. The reason the name RotableButNotReally.
